import OptaveJavaScriptSDK from '../src/main.js';

const optaveClient = new OptaveJavaScriptSDK({
    websocketUrl: process.env.OPTAVE__WEBSOCKET_URL,

    // These parameters are only required when using the authenticate() function.
    // In some cases, the authentication token can be obtained manually or through
    // another process, which makes the authenticate() call unnecessary. In this
    // case, only the openConnection function has to be called, passing the existing token value
    authenticationUrl: process.env.OPTAVE__AUTHENTICATION_URL,
    clientId: process.env.OPTAVE__CLIENT_ID,
    clientSecret: process.env.OPTAVE__CLIENT_SECRET,
});

async function run() {
    // Listen for messages from the WebSocket
    optaveClient.on('message', payload => {
        const message = JSON.parse(payload);
        const { actionType, state, action } = message;
    
        console.log(`Action: ${action} / State: ${state} / Action Type: ${actionType}`);
    });
    
    // Handle errors
    optaveClient.on('error', error => {
        if (typeof error === 'string') {
            console.error(error);
        } else {
            console.error('Error', error);
        }
    })
    
    // After the connection is opened, send a customerinteraction message
    optaveClient.once('open', () => {
        optaveClient.customerInteraction({
            session: {
                session_id: "a1b2c3e6-e5f6-7890-1234-56789abcdef0",
                channel: {
                    browser: "Safari 17.0",
                    device_info: "iOS/18.2, iPhone15,3",
                    device_type: "mobile",
                    language: "en-US",
                    location: "40.7128,-74.0060", // GPS coordinates
                    medium: "chat", // options: "chat", "voice", "email"
                    section: "support_page",
                },
                interface: {
                    app_version: "2.1.0",
                    category: "crm",
                    language: "en-US",
                    name: "my_support_app",
                    type: "custom_components",
                },
                network: {
                    latency_ms: 120
                }
            },
            request: {
                request_id: "a1b2c3d4-e5f6-7890-1234-56789ab2345",
                attributes: {
                    variant: "A"
                },
                connections: {
                    thread_id: "9e8d7c6b-5a49-3827-1605-948372615abc" // REQUIRED
                },
                context: { // generated by optave
                    organization_id: "f7e8d9c0-b1a2-3456-7890-123456789abc", // REQUIRED
                    tenant_id: "a1b2c3d4-e5f6-7890-1234-56789abcdef0", // REQUIRED
                },
                resources: {
                    codes: [
                        {
                            id: "328123-123812312-13023f08asdxjfw0e",
                            label: "Order Number",
                            type: "order_number",
                            value: "ORD-12345",
                        }
                    ],
                    links: [
                        {
                            expires_at: "2025-08-06T00:00:00Z",
                            html: false,
                            id: "20382320302",
                            label: "Complete Payment",
                            type: "payment_link",
                            url: "https://checkout.stripe.com/pay/cs_test...",
                        }
                    ],
                    offers: [
                        {
                            // Please contact your optave representative to define the object you should send here
                        }
                    ],
                },
                scope: {
                    conversations: [ // REQUIRED
                        {
                            content: "Hi, can you help me?",
                            display_name: "John Doe",
                            participant_id: "2c4f8a9b-1d3e-5f70-8293-456789012def", //sent by the client - optional
                            role: "EndUser",
                            timestamp: "2024-01-15T10:30:00.000Z",
                        },
                        {
                            content: "Hello! I'd be happy to assist you today. What can I help you with?",
                            display_name: "Sarah Smith",
                            participant_id: "5b8c9d0e-2f4a-6b1c-9d8e-123456789xyz",
                            role: "Agent",
                            timestamp: "2024-01-15T10:30:15.000Z",
                        }
                    ],
                    interactions: [
                        {
                            content: "Support ticket T12345 has been created for user John Doe",
                            id: "1",
                            name: "ticket_created",
                            role: "System",
                            timestamp: "2024-01-15T10:29:45.000Z",
                        }
                    ]
                },
                settings: {
                    disable_browsing: false,
                    disable_search: false,
                    disable_sources: false,
                    disable_stream: false,
                    disable_tools: false,
                    max_response_length: 2000,
                    override_output_language: "en-US"
                }
            }
        });
    });

    const token = await optaveClient.authenticate();
    optaveClient.openConnection(token);
}

run();