import OptaveJavaScriptSDK from '../src/main.js';

const optaveClient = new OptaveJavaScriptSDK({
    websocketUrl: process.env.OPTAVE__WEBSOCKET_URL,

    // These parameters are only required when using the authenticate() function.
    // In some cases, the authentication token can be obtained manually or through
    // another process, which makes the authenticate() call unnecessary. In this
    // case, only the openConnection function has to be called, passing the existing token value
    authenticationUrl: process.env.OPTAVE__AUTHENTICATION_URL,
    clientId: process.env.OPTAVE__CLIENT_ID,
    clientSecret: process.env.OPTAVE__CLIENT_SECRET,
});

async function run() {
    // Listen for messages from the WebSocket
    optaveClient.on('message', payload => {
        const message = JSON.parse(payload);
        const { actionType, state, action } = message;
    
        console.log(`Action: ${action} / State: ${state} / Action Type: ${actionType}`);
    });
    
    // Handle errors
    optaveClient.on('error', error => {
        if (typeof error === 'string') {
            console.error(error);
        } else {
            console.error('Error:', error);
        }
    });
    
    // When the connection is opened, send an insights message
    optaveClient.once('open', () => {
        optaveClient.insights({
            session: {
                session_id: "a1b2c3e6-e5f6-7890-1234-56789abcdef0",
                channel: {
                    browser: "Safari 17.0",
                    device_info: "iOS/18.2, iPhone15,3",
                    device_type: "mobile",
                    language: "en-US",
                    location: "40.7128,-74.0060", // GPS coordinates
                    medium: "chat", // options: "chat", "voice", "email"
                    section: "support_page",
                },
                interface: {
                    app_version: "2.1.0",
                    category: "crm",
                    language: "en-US",
                    name: "my_support_app",
                    type: "custom_components",
                },
                network: {
                    latency_ms: 120
                }
            },
            request: {
                request_id: "89012345-6789-0123-456789abcdef",
                attributes: {
                    variant: "A",
                },
                connections: {
                    thread_id: "9e8d3c6b-5a4f-3e2d-1c0b-0987654321ab", // REQUIRED
                },
                context: {//generated by optave
                    organization_id: "f7e8d9c0-b1a2-3456-7890-123456789abc", // REQUIRED
                    tenant_id: "a1b2c3d4-e5f6-7890-1234-56789abcdef0", // REQUIRED
                }, 
                scope: {
                    conversations: [ // REQUIRED
                        {
                            content: "Hi, can you help me?",
                            display_name: "John Doe",
                            participant_id: "2c4f8a9b-1d3e-5f70-8293-456789012def",
                            role: "EndUser",
                            timestamp: "2024-01-15T10:30:00.000Z",
                        },
                        {
                            content: "Hello! I'd be happy to assist you today. What can I help you with?",
                            display_name: "Sarah Smith",
                            participant_id: "5b8c9d0e-2f4a-6b1c-9d8e-123456789xyz",
                            role: "Agent",
                            timestamp: "2024-01-15T10:30:15.000Z",
                        }
                ]
                }
            }
        });
    });

    // Authenticate and open the WebSocket connection
    try {
        const token = await optaveClient.authenticate();
        optaveClient.openConnection(token);
    } catch (error) {
        console.error('Failed to authenticate and connect:', error);
    }
}

run();
